### ISSUE TITLE
Build a descent front-end 

### ISSUE THREAD

**Issue by p53ud0k0d3** [p53ud0k0d3/UrlShortener#1]
Build a descent front-end. Arrange the button and input fields. Provide title. Use bootstrap to make it beautiful.

**Comment by agdhruv** [comment]
Hi @p53ud0k0d3 , saw the `help wanted` tag on this issue. I want to start off with open source contribution, how can I help you with this?

**Comment by p53ud0k0d3** [comment]
@agdhruv This is just perfect for u to start. Just some simple things. 
Work on dev branch. 
Use css to make everything beautiful. Arrange components as necessary. Use your imagination. 
After completing, create a pull request to dev branch. 
Good luck.

**Comment by agdhruv** [comment]
@p53ud0k0d3 I am using [this](https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repository) video for help with forking and cloning. I have done the `git branch --set-upstream-to=upstream/master master` step, but what do I do with the dev branch? Could you please help?

**Comment by p53ud0k0d3** [comment]
there are two branches.. dev and master. master is the main branch.
after cloning, run : git checkout dev.  This will switch branch to dev.
Then work. commit. push. create a pr.
u can always run : git checkout
to check which branch u r currently in.

Find the attachment. Keep this in ur fone as a reference.

**Comment by agdhruv** [comment]
Thank you!
PR sent, please check :)

**Comment by p53ud0k0d3** [comment]
@agdhruv Good job. Good luck.

**Comment by agdhruv** [comment]
@p53ud0k0d3 Thank you! Would you happen to know why hasn't the "contributors" section increased to 2? Just wondering.
