### ISSUE TITLE
Create readme content

### ISSUE THREAD

**Issue by p53ud0k0d3** [p53ud0k0d3/UrlShortener#13]
Create readme content. Should list and explain all the features with good formatting. Refer
[https://help.github.com/articles/basic-writing-and-formatting-syntax/](url)

**Comment by mayankkvpy2014** [comment]
i have made a readme file.how do i upload it??
i am new to open source

**Comment by p53ud0k0d3** [comment]
see which branch u r on by running "git branch"
if u r not in dev branch, type "git checkout dev" if u have uncommitted changes, "git checkout -f dev"
do the edits
"git add readme.md"
git commit -m "some message"
git push

then goto github and create a merge request


goodluck

**Comment by mayankkvpy2014** [comment]
kindly see i have made a pulll request
