### ISSUE TITLE
ImportError: No module named services.rebrandly

### ISSUE THREAD

**Issue by luizferreira** [p53ud0k0d3/UrlShortener#22]
Following the Installation and Usage instructions, when I run `python manage.py migrate` I get an `ImportError: No module named services.rebrandly`.

The problem is there is no `__init__.py` file inside `Shortener/services`.

**Comment by vhr121** [comment]
Hi @luizferreira 
There is` __init__.py` inside `shortener/services`.

The problem may be with the python environment that you are using.
Create a new virtual environment and then `pip install -r  requirements.txt`
Before running the server don't forget to `python manage.py migrate`

Following the above procedure must solve the issue.

**Comment by vhr121** [comment]
The issue has been resolved, do close the issue.
