### ISSUE TITLE
Broken 'for the badge' badge

### ISSUE THREAD

**Issue by TheY3TI** [p53ud0k0d3/UrlShortener#31]
Several links in the [readme-file](https://github.com/p53ud0k0d3/UrlShortener/blob/master/README.md) are broken. For example:
* The badge that gets grabbed from [For The Badge](http://forthebadge.com/badges/built-with-swag.svg) does no longer exist.
* The [link](http://www.ellison.rocks/pyshorteners/) to the pyshorteners API

**Comment by modelorona** [comment]
The author seems to have removed the url for it :)

**Comment by paqman85** [comment]
I found the current url for "Built with Swag". Will update readme.

**Comment by kateapault** [comment]
re-updated the pyshorteners link to their readthedocs.io page

**Comment by MAX-EINSTEIN** [comment]
The issue has been fixed
