### ISSUE TITLE
Add more service providers

### ISSUE THREAD

**Issue by p53ud0k0d3** [p53ud0k0d3/UrlShortener#4]
Now we have only 2 service providers; Tinyurl and Is.gd. Add more of these. Some of these service providers need signing in and generating api keys. Do whatever is necessary.
Work on Dev branch and create PR. 
Good luck.

**Comment by arjuntherajeev** [comment]
Interested! How about using Google's URL Shortener (https://developers.google.com/url-shortener/v1/getting_started) ? 
I noticed that the project is in Django. Can I contribute a generic Python script which you could perhaps later port into the Django controller?

**Comment by p53ud0k0d3** [comment]
Yeah project is in django. Why don't you take this opportunity to learn some django. It is very simple. See the views.py, it is just like any other python script. Try it. It will be easy. I will assist you if you need any help.

**Comment by arjuntherajeev** [comment]
Sure, mate! I started learning Django today and it's pretty exciting. I have lots of experience with WEB2PY (another MVC Python framework) and most of the concepts are very similar! Once, I finish my tutorial, I will fork the UrlShortener repo and start coding there. Does that sound fine? :)

**Comment by p53ud0k0d3** [comment]
Sure. Whenever you are ready. 😊

**Comment by ssummun54** [comment]
Any tips for learning Django? I just got done with my first ComSci class that was taught in Python

**Comment by p53ud0k0d3** [comment]
Just follow django documentation. It is easy. Don't spend too much time
memorizing things, start building. U can learn on the go.

**Comment by arjuntherajeev** [comment]
@ssummun54 Yes, Vishnu has a great point. The documentation is really good! 
Also, check out this YouTube playlist - https://www.youtube.com/playlist?list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK 
I am following this right now and it's really interesting and helpful! :)

**Comment by kushagra7589** [comment]
Hi! I saw that pyshorteners provides a lot of service providers and a lot of those do not require login/api_key. Can I add those functionalities in this app?

**Comment by kushagra7589** [comment]
Other than the five service providers you are currently using, there is another one provided by pyshorteners - Osdb.link. Can I add that functionality to the app? It will make the app complete.

**Comment by scomert** [comment]
do you consider to upgrade your pyshorteners version to 0.6.1 ? you can have more services by that version.

**Comment by jdk1997** [comment]
I am interested in adding another service provider. This will also be an opportunity for me to learn some Django. So, can I add another service provider??

**Comment by thisHermit** [comment]
I am interested in working on this. @p53ud0k0d3 , could you please assign me on this?

**Comment by alceil** [comment]
I TOO WANT TO CONTRIBUTE CAN ANYONE GUIDE ME

**Comment by a-fatah** [comment]
I am working on this issue

**Comment by cristinasofia** [comment]
> Yeah project is in django. Why don't you take this opportunity to learn some django. It is very simple. See the views.py, it is just like any other python script. Try it. It will be easy. I will assist you if you need any help.

I would love to contribute :) Assign me? @p53ud0k0d3

**Comment by MAX-EINSTEIN** [comment]
I have added 3 more url shortening services that don't even require any key. Should  I make a pull request now? @p53ud0k0d3

**Comment by MAX-EINSTEIN** [comment]
I have added 5 new url shortening services now and made a pull request:
[https://github.com/p53ud0k0d3/UrlShortener/pull/67](url)

**Comment by MAX-EINSTEIN** [comment]
@p53ud0k0d3 Let me know if I can do anything else... your project is awesome

**Comment by p53ud0k0d3** [comment]
I am very busy these days. I am looking for someone whom I can add as a
collaborator, who can verify all the existing pull requests and merge them
properly. Are you interested?

**Comment by MAX-EINSTEIN** [comment]
I am interested.

**Comment by p53ud0k0d3** [comment]
Cool, I have sent you an invite. please check.

**Comment by MAX-EINSTEIN** [comment]
I accepted the invite. Thanks for making a collaborator. So should I get to work now?  I have few ideas on improving the project. I would be happy if you would like to give your inputs. @p53ud0k0d3 
Also can you merge that pull request I sent or should I merge it?

**Comment by hasan-haider** [comment]
**WANT TO COLLABORATE**
Hey, I added all the open service providers and removed unavailable providers of pyshorteners. Cleaned code by reducing loops and making single loop for efficiency.
Do check pull request.

**Comment by MAX-EINSTEIN** [comment]
More service provider has been added. This issue is being closed.

**Comment by p53ud0k0d3** [comment]
Thanks. You can verify all merge requests and merge them. Please test
before merging. You may use this collaborator role in your portfolio or
resume or wherever you feel like. I will vouch if some enquires.

Thank you
Vishnu
