### ISSUE TITLE
dockerize this application

### ISSUE THREAD

**Issue by Better-Boy** [p53ud0k0d3/UrlShortener#45]
Dockerizing this application will help a lot. Hence, I'll go ahead with dockerizing this application

**Comment by biddwan09** [comment]
Hi @Better-Boy can I work on this issue ?

**Comment by Better-Boy** [comment]
Go for it @biddwan09

**Comment by bjornwelboren** [comment]
Made a PR

**Comment by perun-01** [comment]
is it still open?

**Comment by yellalena** [comment]
is it still open? can I work on this?

**Comment by MAX-EINSTEIN** [comment]
Docker support has been added
