### ISSUE TITLE
Transfer the code base to Django 2.2

### ISSUE THREAD

**Issue by abhishekraj272** [p53ud0k0d3/UrlShortener#50]
I am transferring the code base to Django 2.2. I have started the work.

**Comment by bjornwelboren** [comment]
> I am transferring the code base to Django 2.2. I have started the work.

How is it going?

**Comment by abhishekraj272** [comment]
Will take 2-3 days.

**Comment by MAX-EINSTEIN** [comment]
No progress made yet
